### STAGE C TAG ALONG CODES

SUBMITTED BY : CHIMEREMMA SANDRA AMADI

ID: 1572c1a4b801f000

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.utils
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

In [5]:
df= pd.read_csv('Data_for_UCI_named.csv')
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

In [6]:
df.describe

<bound method NDFrame.describe of           tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975
...        ...       ...       ...       ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193

            p4        g1        g2        g3        g4      stab     stabf
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable
...        ...       ...       ...       ...       ...       ...       ...
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable

[10000 rows x 14 columns]>

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object
dtypes: float64(13), object(1)
memory usage: 1.1+ MB

In [8]:
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [15]:
X = df.drop(columns = 'stabf')
y = df['stabf']
scaler = StandardScaler()
X_norm = pd.DataFrame(scaler.fit_transform(X), columns = X.columns)
X_norm.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab
0,-0.835374,-0.791317,1.141704,1.652103,0.017397,1.079405,-0.017078,-1.092545,0.457467,1.220013,1.321628,1.579026,1.073120
1,1.478297,-0.126705,-0.803111,-1.415043,1.752124,-1.593619,-1.438158,-0.011575,-0.406791,1.230354,0.135424,0.936256,-0.587487
2,1.357093,1.312140,-0.803499,-1.471504,-0.458492,0.098253,-0.062840,0.760963,-1.319852,0.881299,1.146596,-1.513802,-0.332095
3,-1.653138,0.882289,-0.278354,-1.060901,0.284250,0.513904,-1.591046,0.583414,-0.287304,1.647250,1.474543,-0.591750,0.355922
4,-0.771543,0.860108,-0.111670,1.680114,-0.298075,0.287450,-1.376343,1.606636,0.992226,-0.253610,0.481133,1.079063,0.924487

In [16]:
y.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size = 0.2, random_state = 1)

###  QUESTION 14

In [31]:
random_f_clf = RandomForestClassifier(random_state=1)
random_f_clf.fit(X_train, y_train)
random_f_pred = random_f_clf.predict(X_test)

### accuracy :

In [37]:
random_f_pred = random_f_clf.predict(X_test)

accuracy = accuracy_score(y_true=y_test, y_pred=random_f_pred)
print(f'Accuracy: {accuracy:.4f}')

Accuracy: 0.9995

### QUESTION 15- XGboost classifier

In [45]:
 !pip install xgboost

Requirement already satisfied: xgboost in c:\users\dell\anaconda3\lib\site-packages (1.6.2)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.21.5)

In [52]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(random_state=1)
xgb_clf.fit(X_train, y_train)
xgb_pred = xgb_clf.predict(X_test)

In [ ]:
xgb_pred = xgb_clf.predict(X_test)

accuracy = accuracy_score(y_true=y_test, y_pred=xgb_pred)
print(f'Accuracy: {accuracy:.4f}')

### QUESTION 16- LGBM

In [50]:
from lightgbm import LGBMClassifier
lgbm_clf = LGBMClassifier(random_state=1)
lgbm_clf.fit(X_train, y_train)
lgbm_pred = lgbm_clf.predict(X_test)

ModuleNotFoundError: No module named 'lightgbm'

In [49]:
lgbm_pred = lgbm_clf.predict(X_test)
accuracy = accuracy_score(y_true=y_test, y_pred=lgbm_pred)
print(f'Accuracy: {accuracy:.4f}')

NameError: name 'lgbm_clf' is not defined

### QUESTION 17

In [55]:
extra_tree_clf = ExtraTreesClassifier( )
extra_tree_clf.get_params().keys()

NameError: name 'ExtraTreesClassifier' is not defined